server:
  port: 10002

spring:
  application:
    name: account-server
  datasource:
    url: jdbc:mysql://www.littleredhat1997.com:3306/seata?useSSL=false&serverTimezone=UTC
    username: root
    password: Zhangbincheng0
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS