server:
  port: 10000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-server
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: account
          uri: lb://account-server
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: storage
          uri: lb://storage-server
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS