spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: city
          uri: http://localhost:9001
          predicates:
            - Path=/city/**
          filters:
            - StripPrefix=1
        - id: weather
          uri: http://localhost:9002
          predicates:
            - Path=/weather/**
          filters:
            - StripPrefix=1

server:
  port: 9000

eureka:
  #instance:
  #  prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS