server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway

zuul:
  ignoredServices: '*'
  routes:
    sponsor:
      path: /sponsor/**
      service-id: ad-sponsor
      strip-prefix: true
    upload:
      path: /upload/**
      service-id: ad-upload
      strip-prefix: true