spring:
  application:
    name: weather

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true